apiVersion: batch/v1
kind: Job
metadata:
  name: deis-logbomb
  namespace: deis
  labels:
    heritage: deis
spec:
  parallelism: 10
  template:
    metadata:
      labels:
        app: deis-logbomb
    spec:
      restartPolicy: Never
      containers:
      - name: deis-logbomb
        image: # This is set by the update-manifests make target
        imagePullPolicy: Always
        env:
        - name: GO_ROUTINES
          value: "100"
        - name: MESSAGES_PER_GO_ROUTINE
          value: "100"
        - name: LOG_WRITER_TYPE
          value: "nsq"
